/**
 * DEMO SEED DATA — for development and testing only.
 *
 * Every property, host, guest, booking and review below is fictional and is written with
 * `isDemo = true`. Addresses are withheld and coordinates are approximate town-level positions,
 * so no listing points at a real private home. Experiences reference well-known public
 * attractions but are also flagged as demo content pending editorial review.
 */
import type { DestinationKind, ExperienceCategory, PropertyType } from "../src/generated/prisma/enums";

export interface DestinationSeed {
  slug: string;
  name: string;
  kind: DestinationKind;
  parent?: string;
  adminArea?: string;
  latitude: number;
  longitude: number;
  isOrigin?: boolean;
  isPublished?: boolean;
  tagline?: string;
  summary?: string;
  heroImageUrl?: string;
}

export const DESTINATIONS: DestinationSeed[] = [
  { slug: "australia", name: "Australia", kind: "COUNTRY", latitude: -25.2744, longitude: 133.7751 },
  { slug: "nsw", name: "New South Wales", kind: "STATE", parent: "australia", adminArea: "NSW", latitude: -32.0, longitude: 147.0 },
  { slug: "sydney", name: "Sydney", kind: "CITY", parent: "nsw", adminArea: "NSW", latitude: -33.8688, longitude: 151.2093, isOrigin: true },
  {
    slug: "blue-mountains",
    name: "Blue Mountains",
    kind: "REGION",
    parent: "nsw",
    adminArea: "NSW",
    latitude: -33.7125,
    longitude: 150.3119,
    isPublished: true,
    tagline: "Sandstone cliffs, misty valleys and fireside nights.",
    summary: "World Heritage-listed escarpments, bushwalks and cosy village cafés, an easy drive west of Sydney.",
    heroImageUrl: "/demo/scenes/mountains.svg",
  },
  {
    slug: "hunter-valley",
    name: "Hunter Valley",
    kind: "REGION",
    parent: "nsw",
    adminArea: "NSW",
    latitude: -32.7833,
    longitude: 151.2833,
    isPublished: true,
    tagline: "Cellar doors, long lunches and rolling vines.",
    summary: "Australia's oldest wine region, known for Semillon, Shiraz and unhurried weekends.",
    heroImageUrl: "/demo/scenes/vineyard.svg",
  },
  {
    slug: "kiama",
    name: "Kiama",
    kind: "TOWN",
    parent: "nsw",
    adminArea: "NSW",
    latitude: -34.6708,
    longitude: 150.8544,
    isPublished: true,
    tagline: "Blowholes, rock pools and green coastal hills.",
    summary: "A relaxed harbour town on the South Coast with dramatic coastline and dairy-country hinterland.",
    heroImageUrl: "/demo/scenes/coast.svg",
  },
  {
    slug: "jervis-bay",
    name: "Jervis Bay",
    kind: "REGION",
    parent: "nsw",
    adminArea: "NSW",
    latitude: -35.0406,
    longitude: 150.6931,
    isPublished: true,
    tagline: "Famously white sand and dolphins in the bay.",
    summary: "Clear water, national park and some of the whitest sand in Australia.",
    heroImageUrl: "/demo/scenes/bay.svg",
  },
];

/** Hand-entered approximate estimates from Sydney CBD. Replace with ROUTING_API results later. */
export const DRIVE_ESTIMATES = [
  { origin: "sydney", destination: "blue-mountains", minutes: 95, km: 105 },
  { origin: "sydney", destination: "kiama", minutes: 100, km: 120 },
  { origin: "sydney", destination: "hunter-valley", minutes: 130, km: 165 },
  { origin: "sydney", destination: "jervis-bay", minutes: 160, km: 185 },
];

export const HOSTS = [
  { key: "maya", name: "Maya Collins", displayName: "Harper Hill Stays", bio: "Mountain cottages and cabins, looked after by a small local team." },
  { key: "tom", name: "Tom Nguyen", displayName: "Coastline Holiday Co.", bio: "Beach houses and apartments along the South Coast." },
  { key: "priya", name: "Priya Shah", displayName: "Vine & Paddock", bio: "Farm stays and vineyard hideaways in the Hunter." },
] as const;

export const GUESTS = [
  { key: "guest", name: "Sam Taylor" },
  { key: "alex", name: "Alex Chen" },
  { key: "jordan", name: "Jordan Lee" },
  { key: "riley", name: "Riley Martin" },
] as const;

type Scene = "mountains" | "coast" | "vineyard" | "farm" | "cabin" | "bay" | "interior" | "bedroom";

export interface PropertySeed {
  slug: string;
  title: string;
  host: (typeof HOSTS)[number]["key"];
  destination: string;
  type: PropertyType;
  locality: string;
  postcode: string;
  latitude: number;
  longitude: number;
  bedrooms: number;
  beds: number;
  bathrooms: number;
  maxGuests: number;
  nightly: number;
  weekend?: number;
  cleaning: number;
  minNights: number;
  cancellation: "FLEXIBLE" | "MODERATE" | "STRICT";
  amenities: string[];
  scenes: Scene[];
  summary: string;
  description: string;
  houseRules: string;
  status?: "PUBLISHED" | "PENDING_REVIEW";
  /** Overall ratings of demo reviews attached to completed demo stays. */
  reviews?: number[];
}

export const PROPERTIES: PropertySeed[] = [
  {
    slug: "escarpment-edge-cabin",
    title: "Escarpment Edge Cabin",
    host: "maya",
    destination: "blue-mountains",
    type: "CABIN",
    locality: "Blackheath",
    postcode: "2785",
    latitude: -33.64,
    longitude: 150.3,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxGuests: 2,
    nightly: 265,
    weekend: 310,
    cleaning: 70,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["fireplace", "spa", "wifi", "kitchen", "parking", "mountain"],
    scenes: ["cabin", "interior", "bedroom", "mountains"],
    summary: "A timber cabin for two on the edge of the Grose Valley, with a wood fire and outdoor spa.",
    description:
      "Wake to birdsong and valley views from bed. The cabin is built for slow weekends: a wood-burning fireplace, deep outdoor spa and a kitchen stocked with local breakfast provisions.\n\nThe Blackheath village cafés and the start of several clifftop walks are a short drive away.",
    houseRules: "No smoking. No parties or events. Firewood provided — please use the fire screen.",
    reviews: [5, 5, 5],
  },
  {
    slug: "leura-garden-cottage",
    title: "Leura Garden Cottage",
    host: "maya",
    destination: "blue-mountains",
    type: "COTTAGE",
    locality: "Leura",
    postcode: "2780",
    latitude: -33.716,
    longitude: 150.335,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    maxGuests: 6,
    nightly: 295,
    weekend: 340,
    cleaning: 90,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["fireplace", "pet_friendly", "family_friendly", "wifi", "kitchen", "parking", "bbq", "washer", "mountain"],
    scenes: ["mountains", "interior", "bedroom", "cabin"],
    summary: "A 1920s cottage in a cool-climate garden, a short walk from Leura Mall.",
    description:
      "Three bedrooms, an open fire and a fenced garden made for kids and dogs alike. Leura's cafés and boutiques are an easy stroll, and the cliff-top walking tracks are minutes away by car.",
    houseRules: "Dogs welcome (max 2) — please keep them off beds. Quiet hours 10pm–7am.",
    reviews: [5, 4, 5],
  },
  {
    slug: "valley-view-tiny-home",
    title: "Valley View Tiny Home",
    host: "maya",
    destination: "blue-mountains",
    type: "TINY_HOME",
    locality: "Wentworth Falls",
    postcode: "2782",
    latitude: -33.705,
    longitude: 150.37,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxGuests: 2,
    nightly: 189,
    weekend: 219,
    cleaning: 45,
    minNights: 1,
    cancellation: "FLEXIBLE",
    amenities: ["fire_pit", "fireplace", "ev_charging", "wifi", "parking", "mountain"],
    scenes: ["cabin", "mountains", "bedroom"],
    summary: "A compact, off-grid-inspired tiny home with a fire pit and a big window onto the bush.",
    description: "Everything you need and nothing you don't. Solar-assisted power, a loft bed under a skylight, a little wood heater and a fire pit for clear mountain nights. EV charger on site.",
    houseRules: "No smoking. Fire pit use subject to total fire bans.",
  },
  {
    slug: "katoomba-family-retreat",
    title: "Katoomba Family Retreat",
    host: "maya",
    destination: "blue-mountains",
    type: "FAMILY_HOUSE",
    locality: "Katoomba",
    postcode: "2780",
    latitude: -33.719,
    longitude: 150.305,
    bedrooms: 4,
    beds: 6,
    bathrooms: 2.5,
    maxGuests: 9,
    nightly: 420,
    weekend: 480,
    cleaning: 150,
    minNights: 2,
    cancellation: "STRICT",
    amenities: ["family_friendly", "accessible", "wifi", "kitchen", "parking", "washer", "air_conditioning", "bbq", "mountain", "fireplace"],
    scenes: ["mountains", "interior", "bedroom"],
    summary: "Space for the whole crew, with a step-free ground floor and a games room.",
    description: "A generous family home with a step-free main level, a kids' bunk room and a big kitchen table. Close to the major lookouts and family attractions.",
    houseRules: "No parties or events. Quiet hours 10pm–7am.",
    reviews: [5, 5, 4, 5],
  },
  {
    slug: "pokolbin-vineyard-cottage",
    title: "Vineyard Cottage",
    host: "priya",
    destination: "hunter-valley",
    type: "COTTAGE",
    locality: "Pokolbin",
    postcode: "2320",
    latitude: -32.77,
    longitude: 151.3,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    maxGuests: 6,
    nightly: 235,
    weekend: 285,
    cleaning: 80,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["vineyard", "pool", "wifi", "kitchen", "parking", "bbq", "air_conditioning"],
    scenes: ["vineyard", "interior", "bedroom"],
    summary: "A weatherboard cottage among the vines, with a plunge pool and verandah sunsets.",
    description: "Sit on the verandah with a glass of local Semillon as the sun drops behind the Brokenback Range. Several cellar doors are within a short drive — or book a driver and make a day of it.",
    houseRules: "No smoking. Pool is unfenced from the vineyard — children must be supervised.",
    reviews: [5, 5, 5, 4, 5],
  },
  {
    slug: "lovedale-vines-villa",
    title: "Lovedale Vines Villa",
    host: "priya",
    destination: "hunter-valley",
    type: "VILLA",
    locality: "Lovedale",
    postcode: "2325",
    latitude: -32.759,
    longitude: 151.369,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    maxGuests: 8,
    nightly: 520,
    weekend: 620,
    cleaning: 180,
    minNights: 2,
    cancellation: "STRICT",
    amenities: ["vineyard", "pool", "spa", "family_friendly", "ev_charging", "wifi", "kitchen", "parking", "air_conditioning", "washer"],
    scenes: ["vineyard", "interior", "bedroom"],
    summary: "A contemporary villa with a heated pool and spa, set on a working vineyard.",
    description: "Four ensuited bedrooms, a chef's kitchen and a heated pool overlooking the vines. Ideal for celebrations with family or a group of friends.",
    houseRules: "No events without host approval. Quiet hours 11pm–8am.",
    reviews: [5, 4],
  },
  {
    slug: "broke-fordwich-farm-stay",
    title: "Broke Fordwich Farm Stay",
    host: "priya",
    destination: "hunter-valley",
    type: "FARM_STAY",
    locality: "Broke",
    postcode: "2330",
    latitude: -32.75,
    longitude: 151.1,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    maxGuests: 6,
    nightly: 260,
    weekend: 290,
    cleaning: 90,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["farm_stay", "pet_friendly", "family_friendly", "fireplace", "wifi", "kitchen", "parking", "bbq"],
    scenes: ["farm", "interior", "bedroom", "vineyard"],
    summary: "Feed the chooks, collect eggs and watch kangaroos at dusk on a 100-acre property.",
    description: "A restored farmhouse in the quieter Broke Fordwich sub-region. Kids can help with morning farm jobs, and there's plenty of room for dogs to roam (on lead near livestock).",
    houseRules: "Dogs welcome on lead near livestock. Gates must be closed behind you.",
    reviews: [5, 5, 5],
  },
  {
    slug: "cellar-door-studio",
    title: "Cellar Door Studio",
    host: "priya",
    destination: "hunter-valley",
    type: "APARTMENT",
    locality: "Pokolbin",
    postcode: "2320",
    latitude: -32.79,
    longitude: 151.29,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxGuests: 2,
    nightly: 175,
    weekend: 215,
    cleaning: 50,
    minNights: 1,
    cancellation: "FLEXIBLE",
    amenities: ["vineyard", "spa", "wifi", "air_conditioning", "kitchen", "accessible", "parking"],
    scenes: ["interior", "bedroom", "vineyard"],
    summary: "A step-free studio for two, walking distance to a cellar door and restaurant.",
    description: "A light-filled studio with a king bed, kitchenette and a private courtyard with an outdoor spa facing the vines. Step-free access throughout.",
    houseRules: "No smoking. Check-in via lockbox.",
    reviews: [4, 5],
  },
  {
    slug: "blowhole-point-apartment",
    title: "Blowhole Point Apartment",
    host: "tom",
    destination: "kiama",
    type: "APARTMENT",
    locality: "Kiama",
    postcode: "2533",
    latitude: -34.67,
    longitude: 150.86,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    nightly: 245,
    weekend: 295,
    cleaning: 70,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["beach", "wifi", "air_conditioning", "kitchen", "parking", "accessible", "washer"],
    scenes: ["coast", "interior", "bedroom"],
    summary: "Ocean-view apartment a short walk from the Blowhole, cafés and the harbour.",
    description: "Watch the swell roll in from the balcony. Two bedrooms, a lift to the door and secure parking. The coast walk starts just around the corner.",
    houseRules: "No smoking. No parties or events.",
    reviews: [5, 4, 5],
  },
  {
    slug: "werri-beach-house",
    title: "Werri Beach House",
    host: "tom",
    destination: "kiama",
    type: "BEACH_HOUSE",
    locality: "Gerringong",
    postcode: "2534",
    latitude: -34.733,
    longitude: 150.833,
    bedrooms: 4,
    beds: 5,
    bathrooms: 2,
    maxGuests: 8,
    nightly: 480,
    weekend: 560,
    cleaning: 160,
    minNights: 2,
    cancellation: "STRICT",
    amenities: ["beach", "family_friendly", "pet_friendly", "bbq", "parking", "wifi", "kitchen", "washer"],
    scenes: ["coast", "interior", "bedroom"],
    summary: "A classic beach house across the road from the sand, with an outdoor shower and a big deck.",
    description: "Sandy feet welcome. A relaxed four-bedroom house with a huge deck for long lunches, an outdoor shower and a fenced yard for the dog.",
    houseRules: "Dogs welcome. Please rinse sandy gear at the outdoor shower.",
    reviews: [5, 5],
  },
  {
    slug: "jamberoo-valley-farmhouse",
    title: "Jamberoo Valley Farmhouse",
    host: "tom",
    destination: "kiama",
    type: "FARM_STAY",
    locality: "Jamberoo",
    postcode: "2533",
    latitude: -34.647,
    longitude: 150.776,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    maxGuests: 6,
    nightly: 285,
    weekend: 320,
    cleaning: 90,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["farm_stay", "family_friendly", "fireplace", "pet_friendly", "ev_charging", "wifi", "kitchen", "parking"],
    scenes: ["farm", "interior", "bedroom"],
    summary: "Green dairy-country views, a fireplace and the beach just 15 minutes away.",
    description: "A renovated farmhouse on rolling pasture beneath the escarpment. Best of both worlds: farm quiet in the evening, the beach by day.",
    houseRules: "Dogs welcome on lead near cattle. EV charging at cost.",
    reviews: [5, 4, 5],
  },
  {
    slug: "hyams-whitesand-beach-house",
    title: "Whitesand Beach House",
    host: "tom",
    destination: "jervis-bay",
    type: "BEACH_HOUSE",
    locality: "Hyams Beach",
    postcode: "2540",
    latitude: -35.101,
    longitude: 150.69,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    maxGuests: 6,
    nightly: 450,
    weekend: 540,
    cleaning: 140,
    minNights: 2,
    cancellation: "STRICT",
    amenities: ["beach", "bbq", "wifi", "kitchen", "parking", "air_conditioning", "washer"],
    scenes: ["bay", "interior", "bedroom"],
    summary: "Steps from one of the whitest beaches in the country.",
    description: "An airy three-bedroom house a short stroll from the sand. Snorkel, paddle, or just watch for dolphins from the deck.",
    houseRules: "No smoking. No parties or events. Please respect neighbours in this small village.",
    reviews: [5, 5, 5, 5],
  },
  {
    slug: "huskisson-bay-apartment",
    title: "Huskisson Bay Apartment",
    host: "tom",
    destination: "jervis-bay",
    type: "APARTMENT",
    locality: "Huskisson",
    postcode: "2540",
    latitude: -35.041,
    longitude: 150.67,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    maxGuests: 4,
    nightly: 220,
    weekend: 260,
    cleaning: 60,
    minNights: 1,
    cancellation: "FLEXIBLE",
    amenities: ["beach", "pool", "wifi", "air_conditioning", "accessible", "kitchen"],
    scenes: ["bay", "interior", "bedroom"],
    summary: "Walk to the cruise wharf, cafés and the beach from this step-free apartment.",
    description: "A modern two-bedroom apartment with a shared pool, in the heart of Huskisson. Dolphin and whale cruises depart a few minutes' walk away.",
    houseRules: "No smoking. Pool hours 8am–9pm.",
    reviews: [4, 5],
  },
  {
    slug: "vincentia-family-beach-house",
    title: "Vincentia Family Beach House",
    host: "tom",
    destination: "jervis-bay",
    type: "FAMILY_HOUSE",
    locality: "Vincentia",
    postcode: "2540",
    latitude: -35.07,
    longitude: 150.675,
    bedrooms: 4,
    beds: 6,
    bathrooms: 2,
    maxGuests: 10,
    nightly: 390,
    weekend: 460,
    cleaning: 150,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["beach", "family_friendly", "pet_friendly", "pool", "parking", "ev_charging", "wifi", "kitchen", "bbq", "washer"],
    scenes: ["bay", "coast", "interior", "bedroom"],
    summary: "Pool, bunk room and a short walk to calm, kid-friendly beaches.",
    description: "Built for big family holidays: a fenced pool, a bunk room for the kids, a separate living area for the grown-ups and calm bay beaches nearby.",
    houseRules: "Pool fenced — gate must stay closed. Dogs welcome outside only.",
    reviews: [5, 5, 4],
  },
  {
    slug: "callala-bush-tiny-home",
    title: "Callala Bush Tiny Home",
    host: "tom",
    destination: "jervis-bay",
    type: "TINY_HOME",
    locality: "Callala Bay",
    postcode: "2540",
    latitude: -34.995,
    longitude: 150.72,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    maxGuests: 2,
    nightly: 165,
    weekend: 195,
    cleaning: 40,
    minNights: 1,
    cancellation: "FLEXIBLE",
    amenities: ["beach", "pet_friendly", "fire_pit", "parking", "wifi"],
    scenes: ["cabin", "bay", "bedroom"],
    summary: "A tiny home tucked into coastal bush, a few minutes from a quiet bay beach.",
    description: "Simple, beautiful and dog-friendly. Fall asleep to the sound of the bush and wake up for a morning swim.",
    houseRules: "Dogs welcome. Fire pit use subject to total fire bans.",
  },
  {
    // Awaiting admin approval — must NOT appear in public search.
    slug: "megalong-valley-cabin",
    title: "Megalong Valley Cabin",
    host: "maya",
    destination: "blue-mountains",
    type: "CABIN",
    locality: "Megalong Valley",
    postcode: "2785",
    latitude: -33.7,
    longitude: 150.24,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    maxGuests: 4,
    nightly: 230,
    cleaning: 70,
    minNights: 2,
    cancellation: "MODERATE",
    amenities: ["fireplace", "mountain", "parking", "farm_stay"],
    scenes: ["cabin", "mountains"],
    summary: "A secluded valley cabin surrounded by horse paddocks.",
    description: "Pending review demo listing.",
    houseRules: "No smoking.",
    status: "PENDING_REVIEW",
  },
];

export const REVIEW_TEXTS = [
  "Exactly as described and even better in person. We'd happily make the drive again.",
  "Beautifully presented and spotless. The host's local recommendations were spot on.",
  "Such a peaceful spot — we barely left. Perfect for switching off after a long week.",
  "Great base for exploring the area. Easy check-in and everything we needed.",
  "The kids loved it and so did we. Plenty of space and thoughtful touches throughout.",
  "Lovely stay. A couple of small things could be updated, but overall great value.",
  "Worth every minute of the drive. We're already planning a return trip.",
  "Comfortable beds, well-equipped kitchen and a view we won't forget.",
];

export interface ExperienceSeed {
  slug: string;
  destination: string;
  title: string;
  category: ExperienceCategory;
  summary: string;
  durationMinutes?: number;
}

export const EXPERIENCES: ExperienceSeed[] = [
  { slug: "echo-point-three-sisters", destination: "blue-mountains", title: "Three Sisters lookout at Echo Point", category: "LOOKOUT", summary: "The Blue Mountains' best-known view over the Jamison Valley." },
  { slug: "wentworth-falls-walk", destination: "blue-mountains", title: "Wentworth Falls walking tracks", category: "HIKING", summary: "Clifftop and waterfall walks ranging from short strolls to full-day hikes.", durationMinutes: 180 },
  { slug: "hunter-cellar-doors", destination: "hunter-valley", title: "Cellar door tastings around Pokolbin", category: "WINE_TOUR", summary: "Dozens of cellar doors within a short drive — consider a driver or tour." },
  { slug: "hunter-valley-gardens", destination: "hunter-valley", title: "Hunter Valley Gardens", category: "FAMILY_ATTRACTION", summary: "Large themed display gardens, popular with families." },
  { slug: "kiama-blowhole", destination: "kiama", title: "Kiama Blowhole", category: "LOOKOUT", summary: "A famous sea blowhole on the headland beside the harbour." },
  { slug: "kiama-coast-walk", destination: "kiama", title: "Kiama Coast Walk", category: "HIKING", summary: "Coastal track past beaches, headlands and rock formations.", durationMinutes: 150 },
  { slug: "kiama-whale-watching", destination: "kiama", title: "Whale watching from the headlands", category: "WHALE_WATCHING", summary: "Humpbacks pass the coast during the annual migration (roughly May–November)." },
  { slug: "jervis-bay-dolphin-cruise", destination: "jervis-bay", title: "Dolphin and whale cruises from Huskisson", category: "WHALE_WATCHING", summary: "Resident dolphins year-round and migrating whales in season.", durationMinutes: 120 },
  { slug: "white-sands-walk", destination: "jervis-bay", title: "White Sands Walk", category: "HIKING", summary: "An easy walk linking several white-sand beaches.", durationMinutes: 90 },
  { slug: "currambene-creek-kayak", destination: "jervis-bay", title: "Kayaking on Currambene Creek", category: "KAYAKING", summary: "Calm-water paddling through mangroves near Huskisson.", durationMinutes: 120 },
];
